Added a SQLite plugin. Had to remove plugin's System.Data.dll to fix error CS1703. Hopefully this won't cause issues with the plugin later. Proceed with caution.